"""link evidence units to the listing they came from

Revision ID: 10bb0b9fc913
Revises: 67e20a171deb
Created: 2026-09-05 01:50:41.045691
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (autogenerate emits pgvector types)
import sqlalchemy as sa
from alembic import op

revision: str = '10bb0b9fc913'
down_revision: str | None = '67e20a171deb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_unit', sa.Column('source_listing_id', sa.UUID(), nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_evidence_unit_source_listing_id'), 'evidence_unit', 'source_listing', ['source_listing_id'], ['id'], source_schema='core', referent_schema='core', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_evidence_unit_source_listing_id'), 'evidence_unit', schema='core', type_='foreignkey')
    op.drop_column('evidence_unit', 'source_listing_id', schema='core')
    # ### end Alembic commands ###
