"""initial schema: catalogue, evidence, analysis, serving

Revision ID: 67e20a171deb
Revises: 
Created: 2026-09-05 01:02:50.595511
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '67e20a171deb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # A previous failed downgrade can leave enum types behind. Clear them first
    # so this migration is safe to re-run against a partially torn-down database.
    for enum_name in (
        "aspect_key",
        "modality",
        "run_status",
        "source_kind",
        "transmission",
        "fuel_type",
        "vehicle_class",
    ):
        op.execute(f'DROP TYPE IF EXISTS core."{enum_name}"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fusion_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fusion_config')),
    sa.UniqueConstraint('config_hash', name=op.f('uq_fusion_config_config_hash')),
    sa.UniqueConstraint('name', name=op.f('uq_fusion_config_name')),
    schema='analysis'
    )
    op.create_table('aspect',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Enum('ENGINE_GEARBOX', 'RIDE_HANDLING_NVH', 'RUNNING_COST', 'SPACE_COMFORT', 'FEATURES', 'BUILD_QUALITY', 'SAFETY', 'SERVICE_AFTERSALES', 'LONG_TERM_RELIABILITY', name='aspect_key', schema='core'), nullable=False),
    sa.Column('label_car', sa.String(length=80), nullable=False),
    sa.Column('label_two_wheeler', sa.String(length=80), nullable=False),
    sa.Column('aspect_group', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aspect')),
    sa.UniqueConstraint('key', name=op.f('uq_aspect_key')),
    schema='core'
    )
    op.create_table('evidence_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('OWNER_REVIEW', 'EXPERT_REVIEW', 'FORUM', 'VIDEO', 'SOCIAL', 'REGULATORY', 'NEWS', 'DATASET', name='source_kind', schema='core'), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('robots_policy', sa.Text(), nullable=True),
    sa.Column('terms_reviewed_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_rpm', sa.SmallInteger(), nullable=False),
    sa.Column('default_source_prior', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_source')),
    sa.UniqueConstraint('source_key', name=op.f('uq_evidence_source_source_key')),
    schema='core'
    )
    op.create_table('manufacturer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturer')),
    sa.UniqueConstraint('slug', name=op.f('uq_manufacturer_slug')),
    schema='core'
    )
    op.create_table('ingest_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', 'CIRCUIT_OPEN', name='run_status', schema='core'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refs_discovered', sa.Integer(), nullable=False),
    sa.Column('payloads_fetched', sa.Integer(), nullable=False),
    sa.Column('units_inserted', sa.Integer(), nullable=False),
    sa.Column('units_skipped', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['core.evidence_source.id'], name=op.f('fk_ingest_run_source_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_run')),
    schema='core'
    )
    op.create_index('ix_ingest_run_source_started', 'ingest_run', ['source_id', 'started_at'], unique=False, schema='core')
    op.create_table('vehicle_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('vehicle_class', sa.Enum('CAR', 'TWO_WHEELER', name='vehicle_class', schema='core'), nullable=False),
    sa.Column('body_style', sa.String(length=40), nullable=True),
    sa.Column('segment', sa.String(length=40), nullable=True),
    sa.Column('launch_year', sa.SmallInteger(), nullable=True),
    sa.Column('discontinued_year', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['core.manufacturer.id'], name=op.f('fk_vehicle_model_manufacturer_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_model')),
    sa.UniqueConstraint('manufacturer_id', 'slug', name=op.f('uq_vehicle_model_manufacturer_id_slug')),
    schema='core'
    )
    op.create_table('vehicle_variant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('variant_name', sa.String(length=160), nullable=False),
    sa.Column('trim_code', sa.String(length=160), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL', 'DIESEL', 'CNG', 'HYBRID', 'ELECTRIC', name='fuel_type', schema='core'), nullable=False),
    sa.Column('transmission', sa.Enum('MT', 'AT', 'AMT', 'CVT', 'DCT', 'IVT', name='transmission', schema='core'), nullable=False),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('drivetrain', sa.String(length=20), nullable=True),
    sa.Column('engine_power_bhp', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('engine_torque_nm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('arai_mileage_kmpl', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('wheelbase_mm', sa.Integer(), nullable=True),
    sa.Column('ground_clearance_mm', sa.Integer(), nullable=True),
    sa.Column('fuel_tank_litres', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('boot_litres', sa.Integer(), nullable=True),
    sa.Column('seating_capacity', sa.SmallInteger(), nullable=True),
    sa.Column('kerb_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('seat_height_mm', sa.Integer(), nullable=True),
    sa.Column('braking_type', sa.String(length=40), nullable=True),
    sa.Column('ex_showroom_price_min', sa.Integer(), nullable=True),
    sa.Column('ex_showroom_price_max', sa.Integer(), nullable=True),
    sa.Column('price_band', sa.String(length=30), nullable=True),
    sa.Column('production_status', sa.String(length=20), nullable=True),
    sa.Column('spec_completeness', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('spec_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('spec_completeness >= 0 AND spec_completeness <= 1', name=op.f('ck_vehicle_variant_spec_completeness_range')),
    sa.ForeignKeyConstraint(['model_id'], ['core.vehicle_model.id'], name=op.f('fk_vehicle_variant_model_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_variant')),
    sa.UniqueConstraint('model_id', 'trim_code', 'fuel_type', 'transmission', name=op.f('uq_vehicle_variant_model_id_trim_code_fuel_type_transmission')),
    schema='core'
    )
    op.create_index('ix_vehicle_variant_trim_trgm', 'vehicle_variant', ['trim_code'], unique=False, schema='core', postgresql_using='gin', postgresql_ops={'trim_code': 'gin_trgm_ops'})
    op.create_table('raw_payload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['core.ingest_run.id'], name=op.f('fk_raw_payload_ingest_run_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['core.evidence_source.id'], name=op.f('fk_raw_payload_source_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_payload')),
    sa.UniqueConstraint('sha256', name=op.f('uq_raw_payload_sha256')),
    schema='raw'
    )
    op.create_index('ix_raw_payload_source_fetched', 'raw_payload', ['source_id', 'fetched_at'], unique=False, schema='raw')
    op.create_table('evidence_unit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=True),
    sa.Column('raw_payload_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author_ref', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=12), nullable=True),
    sa.Column('modality', sa.Enum('TEXT', 'TRANSCRIPT', 'STRUCTURED', name='modality', schema='core'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating_raw', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('rating_normalized', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_verified_owner', sa.Boolean(), nullable=True),
    sa.Column('helpful_votes', sa.Integer(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('ownership_duration_months', sa.SmallInteger(), nullable=True),
    sa.Column('km_driven', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('spam_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('credibility_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating_normalized IS NULL OR (rating_normalized >= 0 AND rating_normalized <= 1)', name=op.f('ck_evidence_unit_rating_normalized_range')),
    sa.CheckConstraint('spam_probability IS NULL OR (spam_probability >= 0 AND spam_probability <= 1)', name=op.f('ck_evidence_unit_spam_probability_range')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['core.ingest_run.id'], name=op.f('fk_evidence_unit_ingest_run_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['core.vehicle_model.id'], name=op.f('fk_evidence_unit_model_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw.raw_payload.id'], name=op.f('fk_evidence_unit_raw_payload_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['core.evidence_source.id'], name=op.f('fk_evidence_unit_source_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['core.vehicle_variant.id'], name=op.f('fk_evidence_unit_variant_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_unit')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_evidence_unit_content_hash')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_evidence_unit_source_id_external_id')),
    schema='core'
    )
    op.create_index('ix_evidence_unit_variant_published', 'evidence_unit', ['variant_id', 'published_at'], unique=False, schema='core')
    op.create_table('source_listing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_title', sa.Text(), nullable=False),
    sa.Column('raw_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('match_method', sa.String(length=20), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['core.evidence_source.id'], name=op.f('fk_source_listing_source_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['core.vehicle_variant.id'], name=op.f('fk_source_listing_variant_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_listing')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_source_listing_source_id_external_id')),
    schema='core'
    )
    op.create_index('ix_source_listing_unresolved', 'source_listing', ['source_id', 'variant_id'], unique=False, schema='core')
    op.create_table('variant_feature',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('feature_key', sa.String(length=80), nullable=False),
    sa.Column('feature_value', sa.Text(), nullable=True),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['core.vehicle_variant.id'], name=op.f('fk_variant_feature_variant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant_feature')),
    sa.UniqueConstraint('variant_id', 'feature_key', name=op.f('uq_variant_feature_variant_id_feature_key')),
    schema='core'
    )
    op.create_table('verdict',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('fusion_config_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('confidence_low', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('confidence_high', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('effective_sample_size', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sources_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('confidence_low IS NULL OR confidence_high IS NULL OR confidence_low <= overall_score AND overall_score <= confidence_high', name=op.f('ck_verdict_score_inside_interval')),
    sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 10)', name=op.f('ck_verdict_overall_score_range')),
    sa.ForeignKeyConstraint(['fusion_config_id'], ['analysis.fusion_config.id'], name=op.f('fk_verdict_fusion_config_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['core.vehicle_variant.id'], name=op.f('fk_verdict_variant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verdict')),
    sa.UniqueConstraint('variant_id', 'fusion_config_id', name=op.f('uq_verdict_variant_id_fusion_config_id')),
    schema='serving'
    )
    op.create_index('ix_verdict_lookup', 'verdict', ['variant_id', 'fusion_config_id'], unique=False, schema='serving')
    op.create_table('evidence_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_unit_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['evidence_unit_id'], ['core.evidence_unit.id'], name=op.f('fk_evidence_chunk_evidence_unit_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_chunk')),
    sa.UniqueConstraint('evidence_unit_id', 'chunk_index', name=op.f('uq_evidence_chunk_evidence_unit_id_chunk_index')),
    schema='analysis'
    )
    op.create_index('ix_evidence_chunk_embedding', 'evidence_chunk', ['embedding'], unique=False, schema='analysis', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('verdict_aspect',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verdict_id', sa.UUID(), nullable=False),
    sa.Column('aspect_key', sa.Enum('ENGINE_GEARBOX', 'RIDE_HANDLING_NVH', 'RUNNING_COST', 'SPACE_COMFORT', 'FEATURES', 'BUILD_QUALITY', 'SAFETY', 'SERVICE_AFTERSALES', 'LONG_TERM_RELIABILITY', name='aspect_key', schema='core'), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ci_low', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ci_high', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('divergence_index', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('top_covariate', sa.String(length=40), nullable=True),
    sa.Column('covariate_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('divergence_index IS NULL OR (divergence_index >= 0 AND divergence_index <= 1)', name=op.f('ck_verdict_aspect_divergence_range')),
    sa.ForeignKeyConstraint(['verdict_id'], ['serving.verdict.id'], name=op.f('fk_verdict_aspect_verdict_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verdict_aspect')),
    sa.UniqueConstraint('verdict_id', 'aspect_key', name=op.f('uq_verdict_aspect_verdict_id_aspect_key')),
    schema='serving'
    )
    op.create_table('verdict_claim',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verdict_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('claim_template', sa.String(length=60), nullable=False),
    sa.Column('computed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['verdict_id'], ['serving.verdict.id'], name=op.f('fk_verdict_claim_verdict_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verdict_claim')),
    schema='serving'
    )
    op.create_table('aspect_opinion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_unit_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('aspect_key', sa.Enum('ENGINE_GEARBOX', 'RIDE_HANDLING_NVH', 'RUNNING_COST', 'SPACE_COMFORT', 'FEATURES', 'BUILD_QUALITY', 'SAFETY', 'SERVICE_AFTERSALES', 'LONG_TERM_RELIABILITY', name='aspect_key', schema='core'), nullable=False),
    sa.Column('polarity', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('extracted_span', sa.Text(), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_aspect_opinion_confidence_range')),
    sa.CheckConstraint('polarity >= -1 AND polarity <= 1', name=op.f('ck_aspect_opinion_polarity_range')),
    sa.ForeignKeyConstraint(['chunk_id'], ['analysis.evidence_chunk.id'], name=op.f('fk_aspect_opinion_chunk_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_unit_id'], ['core.evidence_unit.id'], name=op.f('fk_aspect_opinion_evidence_unit_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aspect_opinion')),
    schema='analysis'
    )
    op.create_index('ix_aspect_opinion_unit_aspect', 'aspect_opinion', ['evidence_unit_id', 'aspect_key'], unique=False, schema='analysis')
    op.create_table('verdict_claim_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verdict_claim_id', sa.UUID(), nullable=False),
    sa.Column('evidence_unit_id', sa.UUID(), nullable=False),
    sa.Column('contribution_weight', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_unit_id'], ['core.evidence_unit.id'], name=op.f('fk_verdict_claim_evidence_evidence_unit_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verdict_claim_id'], ['serving.verdict_claim.id'], name=op.f('fk_verdict_claim_evidence_verdict_claim_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verdict_claim_evidence')),
    sa.UniqueConstraint('verdict_claim_id', 'evidence_unit_id', name=op.f('uq_verdict_claim_evidence_verdict_claim_id_evidence_unit_id')),
    schema='serving'
    )
    op.create_index('ix_vce_claim_rank', 'verdict_claim_evidence', ['verdict_claim_id', 'rank'], unique=False, schema='serving')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vce_claim_rank', table_name='verdict_claim_evidence', schema='serving')
    op.drop_table('verdict_claim_evidence', schema='serving')
    op.drop_index('ix_aspect_opinion_unit_aspect', table_name='aspect_opinion', schema='analysis')
    op.drop_table('aspect_opinion', schema='analysis')
    op.drop_table('verdict_claim', schema='serving')
    op.drop_table('verdict_aspect', schema='serving')
    op.drop_index('ix_evidence_chunk_embedding', table_name='evidence_chunk', schema='analysis', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('evidence_chunk', schema='analysis')
    op.drop_index('ix_verdict_lookup', table_name='verdict', schema='serving')
    op.drop_table('verdict', schema='serving')
    op.drop_table('variant_feature', schema='core')
    op.drop_index('ix_source_listing_unresolved', table_name='source_listing', schema='core')
    op.drop_table('source_listing', schema='core')
    op.drop_index('ix_evidence_unit_variant_published', table_name='evidence_unit', schema='core')
    op.drop_table('evidence_unit', schema='core')
    op.drop_index('ix_raw_payload_source_fetched', table_name='raw_payload', schema='raw')
    op.drop_table('raw_payload', schema='raw')
    op.drop_index('ix_vehicle_variant_trim_trgm', table_name='vehicle_variant', schema='core', postgresql_using='gin', postgresql_ops={'trim_code': 'gin_trgm_ops'})
    op.drop_table('vehicle_variant', schema='core')
    op.drop_table('vehicle_model', schema='core')
    op.drop_index('ix_ingest_run_source_started', table_name='ingest_run', schema='core')
    op.drop_table('ingest_run', schema='core')
    op.drop_table('manufacturer', schema='core')
    op.drop_table('evidence_source', schema='core')
    op.drop_table('aspect', schema='core')
    op.drop_table('fusion_config', schema='analysis')
    # ### end Alembic commands ###

    # Autogenerate creates these enum types implicitly with the tables above but
    # never drops them, which leaves downgrade/upgrade unable to round trip.
    for enum_name in (
        "aspect_key",
        "modality",
        "run_status",
        "source_kind",
        "transmission",
        "fuel_type",
        "vehicle_class",
    ):
        op.execute(f'DROP TYPE IF EXISTS core."{enum_name}"')

