"""model level evidence

Revision ID: 97c1b2eae7a2
Revises: 10bb0b9fc913
Created: 2026-09-06 01:18:57.150507
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (autogenerate emits pgvector types)
import sqlalchemy as sa
from alembic import op

revision: str = '97c1b2eae7a2'
down_revision: str | None = '10bb0b9fc913'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_listing', sa.Column('model_id', sa.UUID(), nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_source_listing_model_id'), 'source_listing', 'vehicle_model', ['model_id'], ['id'], source_schema='core', referent_schema='core', ondelete='SET NULL')
    # server_default, not just the Python-side default. Autogenerate omits it
    # and the ALTER then fails on any table that already has rows, which
    # production does: 129 verdicts. The default is dropped immediately
    # afterwards so that new rows must state a value rather than inheriting a
    # zero nobody chose.
    op.add_column(
        'verdict',
        sa.Column('model_evidence_count', sa.Integer(), nullable=False, server_default='0'),
        schema='serving',
    )
    op.alter_column('verdict', 'model_evidence_count', server_default=None, schema='serving')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verdict', 'model_evidence_count', schema='serving')
    op.drop_constraint(op.f('fk_source_listing_model_id'), 'source_listing', schema='core', type_='foreignkey')
    op.drop_column('source_listing', 'model_id', schema='core')
    # ### end Alembic commands ###
