"""api quota ledger

Revision ID: b3f81c7d4a20
Revises: 0a0e4737dcb2
Created: 2026-09-07 09:12:44.108233
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (autogenerate emits pgvector types)
import sqlalchemy as sa
from alembic import op

revision: str = 'b3f81c7d4a20'
down_revision: str | None = '0a0e4737dcb2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_quota_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('quota_date', sa.Date(), nullable=False),
    sa.Column('units_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_quota_ledger')),
    sa.UniqueConstraint('source_key', 'quota_date', name='uq_api_quota_source_day'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_quota_ledger', schema='core')
    # ### end Alembic commands ###
