"""raw payload content encoding

Revision ID: c7a4e219b85f
Revises: b3f81c7d4a20
Created: 2026-09-17 18:22:09.441207
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (autogenerate emits pgvector types)
import sqlalchemy as sa
from alembic import op

revision: str = 'c7a4e219b85f'
down_revision: str | None = 'b3f81c7d4a20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Nullable on purpose, and it stays nullable. Null means "stored as
    # received", which is exactly what every existing row is, so this adds a
    # column without rewriting a table that is already too big to rewrite.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'raw_payload',
        sa.Column('content_encoding', sa.String(length=20), nullable=True),
        schema='raw',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_payload', 'content_encoding', schema='raw')
    # ### end Alembic commands ###
