/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Is this instance able to serve?
         *
         *     Deliberately not using the session dependency. If it did, an unreachable
         *     database would raise during dependency resolution, before the handler ran,
         *     and the health endpoint would answer 500 with a SQLAlchemy stack trace: no
         *     diagnosis for us and a stack trace for everyone else. Opening the session
         *     here means the failure is a value this function can report.
         *
         *     503 rather than 200 on failure, because a platform health check reads the
         *     status code and nothing else, and an instance that cannot reach its
         *     database must not be sent traffic.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Every measurement we have recorded, newest first.
         *
         *     Proposal section 18.4. Published rather than kept internal, because a
         *     project that asks you to trust its numbers should show how well those
         *     numbers hold up, including when the answer is unflattering. The first
         *     recorded comparison had our own classifier losing to the lexicon it was
         *     trained from, and that is on this endpoint like everything else.
         *
         *     Empty is a truthful answer. It means nothing has been measured yet.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fusion-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fusion Configs
         * @description What the weighting switch offers.
         *
         *     Switching between these is a lookup by (variant, config), never a
         *     recomputation. That is the only reason the switch is affordable.
         */
        get: operations["fusion_configs_fusion_configs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Variants */
        get: operations["list_variants_variants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants/{variant_id}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Verdict
         * @description THE endpoint. One indexed read, no computation.
         */
        get: operations["get_verdict_variants__variant_id__verdict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{claim_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Claim Evidence
         * @description The traceability drawer.
         *
         *     A read of verdict_claim_evidence ordered by contribution weight, and
         *     nothing else. These rows were written by the fusion engine before any
         *     prose existed, and the score was computed from them, which is why the
         *     citation cannot be wrong.
         */
        get: operations["claim_evidence_claims__claim_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources Health
         * @description Where every source stands. A dead source degrades, it does not break.
         */
        get: operations["sources_health_sources_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AspectOut */
        AspectOut: {
            /** Aspect Key */
            aspect_key: string;
            /** Label */
            label: string;
            /** Score */
            score: number | null;
            /** Ci Low */
            ci_low: number | null;
            /** Ci High */
            ci_high: number | null;
            /** Support Count */
            support_count: number;
            /** Divergence Index */
            divergence_index: number | null;
            /** Agreement */
            agreement: string;
            /** Top Covariate */
            top_covariate?: string | null;
            covariate_explanation?: components["schemas"]["CovariateExplanation"] | null;
            /** Claim Id */
            claim_id?: string | null;
        };
        /** ClaimEvidenceOut */
        ClaimEvidenceOut: {
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /** Aspect Key */
            aspect_key: string;
            /** Score */
            score: number;
            /** Total Contributors */
            total_contributors: number;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
        };
        /** CovariateExplanation */
        CovariateExplanation: {
            /** Covariate */
            covariate: string;
            /** Explained Share */
            explained_share: number;
            /** Groups */
            groups: components["schemas"]["CovariateGroup"][];
        };
        /** CovariateGroup */
        CovariateGroup: {
            /** Value */
            value: string;
            /** Score */
            score: number;
            /** Weight Share */
            weight_share: number;
            /** Count */
            count: number;
        };
        /**
         * EvalRunOut
         * @description One recorded measurement, for the public metrics page.
         */
        EvalRunOut: {
            /** Component */
            component: string;
            /** System */
            system: string;
            /** N Items */
            n_items: number;
            /** Primary Metric */
            primary_metric: string;
            /** Primary Value */
            primary_value: number;
            /** Git Sha */
            git_sha: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source */
            source: string;
            /** Source Kind */
            source_kind: string;
            /** Url */
            url: string | null;
            /** Text */
            text: string;
            /** Published At */
            published_at: string | null;
            /** Is Verified Owner */
            is_verified_owner: boolean | null;
            /** Ownership Duration Months */
            ownership_duration_months: number | null;
            /** Km Driven */
            km_driven: number | null;
            /** Rating Normalized */
            rating_normalized: number | null;
            /** Contribution Weight */
            contribution_weight: number;
            /** Rank */
            rank: number;
        };
        /** FusionConfigOut */
        FusionConfigOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Description */
            description: string | null;
            /** Is Default */
            is_default: boolean;
            /** Display Order */
            display_order: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Database */
            database: boolean;
            /** Variants */
            variants: number;
            /** Verdicts */
            verdicts: number;
        };
        /** SourceHealthOut */
        SourceHealthOut: {
            /** Source Key */
            source_key: string;
            /** Display Name */
            display_name: string;
            /** Kind */
            kind: string;
            /** Is Enabled */
            is_enabled: boolean;
            /** Status */
            status: string | null;
            /** Last Success */
            last_success: string | null;
            /** Units Total */
            units_total: number;
            /** Error Rate */
            error_rate: number | null;
            /** Last Error */
            last_error: string | null;
        };
        /** SpecOut */
        SpecOut: {
            /** Engine Cc */
            engine_cc?: number | null;
            /** Engine Power Bhp */
            engine_power_bhp?: number | null;
            /** Arai Mileage Kmpl */
            arai_mileage_kmpl?: number | null;
            /** Seating Capacity */
            seating_capacity?: number | null;
            /** Boot Litres */
            boot_litres?: number | null;
            /** Kerb Weight Kg */
            kerb_weight_kg?: number | null;
            /** Seat Height Mm */
            seat_height_mm?: number | null;
            /** Braking Type */
            braking_type?: string | null;
            /**
             * Spec Completeness
             * @default 0
             */
            spec_completeness: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantSummary */
        VariantSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Manufacturer */
            manufacturer: string;
            /** Model */
            model: string;
            /** Model Slug */
            model_slug: string;
            /** Vehicle Class */
            vehicle_class: string;
            /** Variant Name */
            variant_name: string;
            /** Fuel Type */
            fuel_type: string;
            /** Transmission */
            transmission: string;
            /** Price Min */
            price_min?: number | null;
            /** Price Max */
            price_max?: number | null;
            /** Overall Score */
            overall_score?: number | null;
            /** Confidence Low */
            confidence_low?: number | null;
            /** Confidence High */
            confidence_high?: number | null;
            /**
             * Evidence Count
             * @default 0
             */
            evidence_count: number;
            /**
             * Model Evidence Count
             * @default 0
             */
            model_evidence_count: number;
            /**
             * Is Suppressed
             * @default false
             */
            is_suppressed: boolean;
        };
        /** VerdictOut */
        VerdictOut: {
            variant: components["schemas"]["VariantSummary"];
            specs: components["schemas"]["SpecOut"];
            /** Fusion */
            fusion: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Overall Score */
            overall_score: number | null;
            /** Confidence Low */
            confidence_low: number | null;
            /** Confidence High */
            confidence_high: number | null;
            /** Is Suppressed */
            is_suppressed: boolean;
            /** Suppression Reason */
            suppression_reason: string | null;
            /** Evidence Count */
            evidence_count: number;
            /** Model Evidence Count */
            model_evidence_count: number;
            /** Effective Sample Size */
            effective_sample_size: number | null;
            /** Sources Used */
            sources_used: string[];
            /** Aspects */
            aspects: components["schemas"]["AspectOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The database is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: {
                component?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fusion_configs_fusion_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FusionConfigOut"][];
                };
            };
        };
    };
    list_variants_variants_get: {
        parameters: {
            query?: {
                /** @description Free text over manufacturer, model and variant. */
                q?: string | null;
                vehicle_class?: string | null;
                fusion?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verdict_variants__variant_id__verdict_get: {
        parameters: {
            query?: {
                fusion?: string | null;
            };
            header?: never;
            path: {
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_evidence_claims__claim_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimEvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_health_sources_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceHealthOut"][];
                };
            };
        };
    };
}
