/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Cheapest possible credential check.
         *
         *     The sign-in form calls this rather than a real page, so a wrong password
         *     costs one row-free request instead of the heaviest query on the surface.
         */
        get: operations["whoami_admin_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Connector Health
         * @description One card per source: is it alive, when did it last work, what broke.
         *
         *     The public /sources/health answers "should a reader trust this corpus".
         *     This answers "what do I have to fix tonight", so it carries the things a
         *     reader has no use for: how long the last run took, how many units it
         *     actually inserted against how many it skipped as duplicates, and the last
         *     error in full rather than summarised.
         */
        get: operations["connector_health_admin_connectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ingest Runs
         * @description Every run, newest first. The log you read when last night went wrong.
         */
        get: operations["ingest_runs_admin_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/freshness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Freshness
         * @description Source by model, coloured by age. Coverage holes become visible.
         *
         *     One grouped aggregate rather than a query per cell. A model with no cell
         *     for a source has never had anything collected from it, and that absence is
         *     the whole point of the grid: it is the shape of what we are missing, which
         *     a list of what we have cannot show.
         */
        get: operations["freshness_admin_freshness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coverage
         * @description Where seeding effort should go next, rather than where it feels needed.
         *
         *     A suppressed variant is not a bug, it is the evidence floor doing its job.
         *     What an operator needs is which ones are close to clearing it and which
         *     are nowhere near, because those are different problems: the first wants
         *     one more source, the second wants a decision about whether the vehicle
         *     belongs in the catalogue at all.
         */
        get: operations["coverage_admin_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/adjudication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Adjudication Queue
         * @description Listings the resolver would not place, for a person to decide.
         *
         *     Human-in-the-loop by design rather than as an admission of failure. The
         *     resolver is deliberately unwilling to guess below its confidence floor,
         *     and something has to happen to what it refuses, otherwise the floor just
         *     silently loses evidence.
         *
         *     Ordered by how much evidence is waiting behind each decision, so an hour
         *     spent here buys the most it can.
         */
        get: operations["adjudication_queue_admin_adjudication_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/adjudication/{listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjudicate
         * @description A person's decision about one listing. The only write on this surface.
         *
         *     Recorded as match_method='human' so it is never mistaken for something the
         *     resolver worked out, and so a later evaluation can separate what we were
         *     told from what we inferred. That distinction is the entire value of this
         *     queue: a human decision mixed indistinguishably into automated ones is a
         *     gold set contaminated by its own answers.
         *
         *     The verdict does not move until the pipeline runs again. Fusion is a batch
         *     stage and this endpoint deliberately does not reach into it, because a
         *     request that triggers a recomputation is a request that can time out
         *     halfway through one.
         */
        post: operations["adjudicate_admin_adjudication__listing_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fusion-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fusion Configs
         * @description Every weighting, its parameters, and how many verdicts it actually has.
         *
         *     Read-only, and that is a decision rather than an unfinished feature.
         *     Creating a configuration here would put it on the public switch
         *     immediately, because /fusion-configs lists whatever exists, while its
         *     verdicts would not exist until the pipeline next ran. Every variant would
         *     answer "no verdict" under the new weighting and the flagship control would
         *     be visibly broken until morning.
         *
         *     A weighting is only real once its verdicts are computed, so creating one
         *     belongs where the computation happens: `revix fuse` in the pipeline. What
         *     an operator needs here is to see what exists and whether it is fully
         *     populated, and that is what this returns.
         */
        get: operations["fusion_configs_admin_fusion_configs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Is this instance able to serve?
         *
         *     Deliberately not using the session dependency. If it did, an unreachable
         *     database would raise during dependency resolution, before the handler ran,
         *     and the health endpoint would answer 500 with a SQLAlchemy stack trace: no
         *     diagnosis for us and a stack trace for everyone else. Opening the session
         *     here means the failure is a value this function can report.
         *
         *     503 rather than 200 on failure, because a platform health check reads the
         *     status code and nothing else, and an instance that cannot reach its
         *     database must not be sent traffic.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Every measurement we have recorded, newest first.
         *
         *     Proposal section 18.4. Published rather than kept internal, because a
         *     project that asks you to trust its numbers should show how well those
         *     numbers hold up, including when the answer is unflattering. The first
         *     recorded comparison had our own classifier losing to the lexicon it was
         *     trained from, and that is on this endpoint like everything else.
         *
         *     Empty is a truthful answer. It means nothing has been measured yet.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fusion-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fusion Configs
         * @description What the weighting switch offers.
         *
         *     Switching between these is a lookup by (variant, config), never a
         *     recomputation. That is the only reason the switch is affordable.
         */
        get: operations["fusion_configs_fusion_configs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Variants */
        get: operations["list_variants_variants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants/{variant_id}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Verdict
         * @description THE endpoint. One indexed read, no computation.
         */
        get: operations["get_verdict_variants__variant_id__verdict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{claim_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Claim Evidence
         * @description The traceability drawer.
         *
         *     A read of verdict_claim_evidence ordered by contribution weight, and
         *     nothing else. These rows were written by the fusion engine before any
         *     prose existed, and the score was computed from them, which is why the
         *     citation cannot be wrong.
         */
        get: operations["claim_evidence_claims__claim_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources Health
         * @description Where every source stands. A dead source degrades, it does not break.
         */
        get: operations["sources_health_sources_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdjudicationDecision
         * @description A person's answer. All three fields absent means "not one of ours".
         */
        AdjudicationDecision: {
            /** Variant Id */
            variant_id?: string | null;
            /** Model Id */
            model_id?: string | null;
            /**
             * Is Rejection
             * @default false
             */
            is_rejection: boolean;
        };
        /** AdjudicationItemOut */
        AdjudicationItemOut: {
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /** Source Key */
            source_key: string;
            /** Raw Title */
            raw_title: string;
            /** Url */
            url: string | null;
            /** Match Method */
            match_method: string | null;
            /** Match Confidence */
            match_confidence: number | null;
            /** Resolved Model Id */
            resolved_model_id: string | null;
            /** Evidence Waiting */
            evidence_waiting: number;
        };
        /** AspectOut */
        AspectOut: {
            /** Aspect Key */
            aspect_key: string;
            /** Label */
            label: string;
            /** Score */
            score: number | null;
            /** Ci Low */
            ci_low: number | null;
            /** Ci High */
            ci_high: number | null;
            /** Support Count */
            support_count: number;
            /** Divergence Index */
            divergence_index: number | null;
            /** Agreement */
            agreement: string;
            /** Top Covariate */
            top_covariate?: string | null;
            covariate_explanation?: components["schemas"]["CovariateExplanation"] | null;
            /** Claim Id */
            claim_id?: string | null;
        };
        /** ClaimEvidenceOut */
        ClaimEvidenceOut: {
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /** Aspect Key */
            aspect_key: string;
            /** Score */
            score: number;
            /** Total Contributors */
            total_contributors: number;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
        };
        /** ConnectorHealthOut */
        ConnectorHealthOut: {
            /** Source Key */
            source_key: string;
            /** Display Name */
            display_name: string;
            /** Kind */
            kind: string;
            /** Is Enabled */
            is_enabled: boolean;
            /** Status */
            status: string | null;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Hours Since Success */
            hours_since_success: number | null;
            /** Is Stale */
            is_stale: boolean;
            /** Last Run Seconds */
            last_run_seconds: number | null;
            /** Units Total */
            units_total: number;
            /** Units Inserted */
            units_inserted: number;
            /** Units Skipped */
            units_skipped: number;
            /** Error Count */
            error_count: number;
            /** Last Error */
            last_error: string | null;
        };
        /** CovariateExplanation */
        CovariateExplanation: {
            /** Covariate */
            covariate: string;
            /** Explained Share */
            explained_share: number;
            /** Groups */
            groups: components["schemas"]["CovariateGroup"][];
        };
        /** CovariateGroup */
        CovariateGroup: {
            /** Value */
            value: string;
            /** Score */
            score: number;
            /** Weight Share */
            weight_share: number;
            /** Count */
            count: number;
        };
        /** CoverageRowOut */
        CoverageRowOut: {
            /**
             * Variant Id
             * Format: uuid
             */
            variant_id: string;
            /** Manufacturer */
            manufacturer: string;
            /** Model */
            model: string;
            /** Variant Name */
            variant_name: string;
            /** Vehicle Class */
            vehicle_class: string;
            /** Evidence Count */
            evidence_count: number;
            /** Model Evidence Count */
            model_evidence_count: number;
            /** Distinct Sources */
            distinct_sources: number;
            /** Is Suppressed */
            is_suppressed: boolean;
            /** Suppression Reason */
            suppression_reason: string | null;
            /** Units Short Of Floor */
            units_short_of_floor: number;
            /** Sources Short Of Floor */
            sources_short_of_floor: number;
        };
        /**
         * EvalRunOut
         * @description One recorded measurement, for the public metrics page.
         */
        EvalRunOut: {
            /** Component */
            component: string;
            /** System */
            system: string;
            /** N Items */
            n_items: number;
            /** Primary Metric */
            primary_metric: string;
            /** Primary Value */
            primary_value: number;
            /** Git Sha */
            git_sha: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source */
            source: string;
            /** Source Kind */
            source_kind: string;
            /** Url */
            url: string | null;
            /** Text */
            text: string;
            /** Published At */
            published_at: string | null;
            /** Is Verified Owner */
            is_verified_owner: boolean | null;
            /** Ownership Duration Months */
            ownership_duration_months: number | null;
            /** Km Driven */
            km_driven: number | null;
            /** Rating Normalized */
            rating_normalized: number | null;
            /** Contribution Weight */
            contribution_weight: number;
            /** Rank */
            rank: number;
        };
        /** FreshnessCellOut */
        FreshnessCellOut: {
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /** Source Key */
            source_key: string;
            /** Last Collected At */
            last_collected_at: string | null;
            /** Hours Since */
            hours_since: number | null;
            /** Units */
            units: number;
        };
        /**
         * FreshnessOut
         * @description A grid rather than a list, because the absences are the information.
         */
        FreshnessOut: {
            /** Sources */
            sources: string[];
            /** Models */
            models: {
                [key: string]: string;
            }[];
            /** Cells */
            cells: components["schemas"]["FreshnessCellOut"][];
        };
        /** FusionConfigAdminOut */
        FusionConfigAdminOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Description */
            description: string | null;
            /** Is Default */
            is_default: boolean;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Verdict Count */
            verdict_count: number;
            /** Variant Count */
            variant_count: number;
            /** Is Complete */
            is_complete: boolean;
        };
        /** FusionConfigOut */
        FusionConfigOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Description */
            description: string | null;
            /** Is Default */
            is_default: boolean;
            /** Display Order */
            display_order: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Database */
            database: boolean;
            /** Variants */
            variants: number;
            /** Verdicts */
            verdicts: number;
        };
        /** IngestRunOut */
        IngestRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Key */
            source_key: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Refs Discovered */
            refs_discovered: number;
            /** Payloads Fetched */
            payloads_fetched: number;
            /** Units Inserted */
            units_inserted: number;
            /** Units Skipped */
            units_skipped: number;
            /** Error Count */
            error_count: number;
            /** Last Error */
            last_error: string | null;
        };
        /** SourceHealthOut */
        SourceHealthOut: {
            /** Source Key */
            source_key: string;
            /** Display Name */
            display_name: string;
            /** Kind */
            kind: string;
            /** Is Enabled */
            is_enabled: boolean;
            /** Status */
            status: string | null;
            /** Last Success */
            last_success: string | null;
            /** Units Total */
            units_total: number;
            /** Error Rate */
            error_rate: number | null;
            /** Last Error */
            last_error: string | null;
        };
        /** SpecOut */
        SpecOut: {
            /** Engine Cc */
            engine_cc?: number | null;
            /** Engine Power Bhp */
            engine_power_bhp?: number | null;
            /** Arai Mileage Kmpl */
            arai_mileage_kmpl?: number | null;
            /** Seating Capacity */
            seating_capacity?: number | null;
            /** Boot Litres */
            boot_litres?: number | null;
            /** Kerb Weight Kg */
            kerb_weight_kg?: number | null;
            /** Seat Height Mm */
            seat_height_mm?: number | null;
            /** Braking Type */
            braking_type?: string | null;
            /**
             * Spec Completeness
             * @default 0
             */
            spec_completeness: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantSummary */
        VariantSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Manufacturer */
            manufacturer: string;
            /** Model */
            model: string;
            /** Model Slug */
            model_slug: string;
            /** Vehicle Class */
            vehicle_class: string;
            /** Variant Name */
            variant_name: string;
            /** Fuel Type */
            fuel_type: string;
            /** Transmission */
            transmission: string;
            /** Price Min */
            price_min?: number | null;
            /** Price Max */
            price_max?: number | null;
            /** Overall Score */
            overall_score?: number | null;
            /** Confidence Low */
            confidence_low?: number | null;
            /** Confidence High */
            confidence_high?: number | null;
            /**
             * Evidence Count
             * @default 0
             */
            evidence_count: number;
            /**
             * Model Evidence Count
             * @default 0
             */
            model_evidence_count: number;
            /**
             * Is Suppressed
             * @default false
             */
            is_suppressed: boolean;
        };
        /** VerdictOut */
        VerdictOut: {
            variant: components["schemas"]["VariantSummary"];
            specs: components["schemas"]["SpecOut"];
            /** Fusion */
            fusion: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Overall Score */
            overall_score: number | null;
            /** Confidence Low */
            confidence_low: number | null;
            /** Confidence High */
            confidence_high: number | null;
            /** Is Suppressed */
            is_suppressed: boolean;
            /** Suppression Reason */
            suppression_reason: string | null;
            /** Evidence Count */
            evidence_count: number;
            /** Model Evidence Count */
            model_evidence_count: number;
            /** Effective Sample Size */
            effective_sample_size: number | null;
            /** Sources Used */
            sources_used: string[];
            /** Aspects */
            aspects: components["schemas"]["AspectOut"][];
        };
        /**
         * WhoAmIOut
         * @description What the sign-in form checks against.
         */
        WhoAmIOut: {
            /** Username */
            username: string;
            /** Authenticated */
            authenticated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    whoami_admin_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIOut"];
                };
            };
        };
    };
    connector_health_admin_connectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorHealthOut"][];
                };
            };
        };
    };
    ingest_runs_admin_runs_get: {
        parameters: {
            query?: {
                /** @description Filter to one source key. */
                source?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    freshness_admin_freshness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreshnessOut"];
                };
            };
        };
    };
    coverage_admin_coverage_get: {
        parameters: {
            query?: {
                /** @description Only variants below the evidence floor. */
                only_suppressed?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjudication_queue_admin_adjudication_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdjudicationItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjudicate_admin_adjudication__listing_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjudicationDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdjudicationItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fusion_configs_admin_fusion_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FusionConfigAdminOut"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The database is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: {
                component?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fusion_configs_fusion_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FusionConfigOut"][];
                };
            };
        };
    };
    list_variants_variants_get: {
        parameters: {
            query?: {
                /** @description Free text over manufacturer, model and variant. */
                q?: string | null;
                vehicle_class?: string | null;
                fusion?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verdict_variants__variant_id__verdict_get: {
        parameters: {
            query?: {
                fusion?: string | null;
            };
            header?: never;
            path: {
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_evidence_claims__claim_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimEvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_health_sources_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceHealthOut"][];
                };
            };
        };
    };
}
